# INFORMATION
* TEST ON COMPUTER GRAPHICS
* STUDENT:
  * CODE: 2052904
  * NAME: Nguyễn Đức Danh

#Provided functions
This section contains code for functions being used in the following sections


In [61]:
"""
RUN THIS CELL TO DEFINE FUNCTIONS
"""
import itertools
import numpy as np
np.set_printoptions(formatter={'all':lambda x: "{:7.3f}".format(x)})

"""
point4d: to ensure and transform "Point" (parameter) to a point in Homogeneous system (i.e., in 4D)
* Point: can be one of the following type:
  > Python list, shape: (3,) or (4,)
  > numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: numpy array, shape: (4,1)
"""
def point4d(Point):
  if isinstance(Point, list):
    Point = np.array(Point)
  
  if isinstance(Point, np.ndarray):
    Point = Point.ravel()
    assert (Point.shape[0] == 3) or (Point.shape[0] == 4), "Point: must be in 3d or 4d"
    if Point.shape[0] == 4:
      assert Point[3] != 0, "w of homo-point must be different to 0"
      return Point.reshape(-1,1)
    else: #in 3D
      Phomo = np.ones((4, 1), dtype=Point.dtype)
      Phomo[:3] = Point.reshape(-1, 1)
      return Phomo
  else:
    raise "Point must be a numpy"

"""
point3d: to ensure and transform "Point" (parameter) to a point in 3D-space
* Point: can be one of the following type:
  > Python list, shape: (3,) or (4,)
  > numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: numpy array, shape: (3,1)
"""
def point3d(Point):
  if isinstance(Point, list):
    Point = np.array(Point)
  
  if isinstance(Point, np.ndarray):
    Point = Point.ravel()
    assert (Point.shape[0] == 3) or (Point.shape[0] == 4), "Point: must be in 3d or 4d"
    if Point.shape[0] == 4:
      assert Point[3] != 0, "w of homo-point must be different to 0"
      return Point[:3].reshape(-1,1)
    else: #in 3D
      return Point.reshape(-1, 1)
  else:
    raise "Point must be a numpy"


"""
vec4d: to ensure and transform "Vector" (parameter) to a vector in Homo. System (i.e., in 4D)
* Vector: can be one of the following type:
  > Python list, shape: (3,) or (4,)
  > numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: numpy array, shape: (4,1); NOTE: the last coordinate is 0 (for vector)
"""
def vec4d(Vector):
  if isinstance(Vector, list):
    Vector = np.array(Vector)
  vhomo = np.zeros((4, 1), dtype=Vector.dtype)
  vhomo[:3] = Vector.ravel()[:3].reshape(-1, 1)
  return vhomo

"""
vec3d: to ensure and transform "Vector" (parameter) to a vector in 3D-space
* Vector: can be one of the following type:
  > Python list, shape: (3,) or (4,)
  > numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: numpy array, shape: (3,1)
"""
def vec3d(Vector):
  if isinstance(Vector, list):
    Vector = np.array(Vector)
  Vector = Vector.ravel()
  assert (Vector.shape[0] == 3) or (Vector.shape[0] == 4), "Vector: must be in 3d or 4d"
  return Vector.ravel()[:3].reshape(-1, 1)

## Demos for using the provided functions

In [62]:
# Demo for using point4d
p1 = point4d([1, 2, 3])
p2 = point4d([1, 2, 3, 4])
p3 = point4d(np.array([1, 2, 3]))
p4 = point4d(np.array([1, 2, 3, 4]))

print(p1, "\n")
print(p2, "\n")
print(p3, "\n")
print(p4, "\n")

[[  1.000]
 [  2.000]
 [  3.000]
 [  1.000]] 

[[  1.000]
 [  2.000]
 [  3.000]
 [  4.000]] 

[[  1.000]
 [  2.000]
 [  3.000]
 [  1.000]] 

[[  1.000]
 [  2.000]
 [  3.000]
 [  4.000]] 



In [63]:
# Demo for using point3d
p1 = point3d([1, 2, 3])
p2 = point3d([1, 2, 3, 4])
p3 = point3d(np.array([1, 2, 3]))
p4 = point3d(np.array([1, 2, 3, 4]))

print(p1, "\n")
print(p2, "\n")
print(p3, "\n")
print(p4, "\n")

[[  1.000]
 [  2.000]
 [  3.000]] 

[[  1.000]
 [  2.000]
 [  3.000]] 

[[  1.000]
 [  2.000]
 [  3.000]] 

[[  1.000]
 [  2.000]
 [  3.000]] 



In [64]:
# Demo for using vec4d
v1 = vec4d([1, 2, 3])
v2 = vec4d([1, 2, 3, 4])
v3 = vec4d(np.array([1, 2, 3]))
v4 = vec4d(np.array([1, 2, 3, 4]))

print(v1, "\n")
print(v2, "\n")
print(v3, "\n")
print(v4, "\n")

[[  1.000]
 [  2.000]
 [  3.000]
 [  0.000]] 

[[  1.000]
 [  2.000]
 [  3.000]
 [  0.000]] 

[[  1.000]
 [  2.000]
 [  3.000]
 [  0.000]] 

[[  1.000]
 [  2.000]
 [  3.000]
 [  0.000]] 



In [65]:
# Demo for using vec3d
v1 = vec3d([1, 2, 3])
v2 = vec3d([1, 2, 3, 4])
v3 = vec3d(np.array([1, 2, 3]))
v4 = vec3d(np.array([1, 2, 3, 4]))

print(v1, "\n")
print(v2, "\n")
print(v3, "\n")
print(v4, "\n")

[[  1.000]
 [  2.000]
 [  3.000]] 

[[  1.000]
 [  2.000]
 [  3.000]] 

[[  1.000]
 [  2.000]
 [  3.000]] 

[[  1.000]
 [  2.000]
 [  3.000]] 



#Question 1: Define some functions
Fill your code for the following functions (right after **#YOUR CODE IS HERE**)

In [87]:
"""
normal_of_face: compute the normal vector of the plane defined by three vertices: A, B, C
* A, B, C: can be one the following:
  > numpy array, shape: (3,) or (3,1)
  > python list: (3,)
* return: numpy array, shape: (3,1)
"""
def normal_of_face(A, B, C):
    v1 = B - A
    v2 = C - A
    normal = np.cross(v1, v2)
    normal = normal / np.linalg.norm(normal)
    return normal
    

"""
normal_of: compute the normal vector of the plane defined by two vectors: v1 and v2
* v1, v2: numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: numpy array, shape: (3,1)
"""
def normal_of(v1, v2):

    v1 = v1.flatten()
    v2 = v2.flatten()
    normal = np.cross(v1, v2)
    normal = normal / np.linalg.norm(normal)
    return normal

"""
averaged: compute the averaged vector of n1, n2, n3
* n1, n2, n3: numpy array, shape: (3,); (3,1);
* return: numpy array, shape: (3,1)
"""
def averaged(n1, n2, n3):
    n1 = np.array(n1).reshape((3,1))
    n2 = np.array(n2).reshape((3,1))
    n3 = np.array(n3).reshape((3,1))
    n = (n1 + n2 + n3) / 3.0
    n = n / np.linalg.norm(n)
    return n
    

"""
area: compute the area (dien-tich) of the triangle defined three vertices: A, B, C
* A, B, C: numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: real value (scalar)
"""
def area(A, B, C):
    v1 = B - A
    v2 = C - A
    normal = np.cross(v1, v2)
  
    return 0.5*np.linalg.norm(normal)


"""
interpolate: 
  >>> P is a point in triangle ABC.
  >>> vA, vB, vC are color, normals (any values) associated with vertices A, B, C respectively
  >>> interpolate: determine the value associated with point P, using BaryCentric Approximation

* A, B, C, P: numpy array, shape: (3, ); (3,1)
* vA, vB, vC: numpy array, shape: (3, ); (3,1) or any values of the same type
* return: value of same type with vA, vB, vC
"""
def interpolate(A, B, C, vA, vB, vC, P):
    v0 = B - A
    v1 = C - A
    v2 = P - A
    d00 = np.dot(v0, v0)
    d01 = np.dot(v0, v1)
    d11 = np.dot(v1, v1)
    d20 = np.dot(v2, v0)
    d21 = np.dot(v2, v1)
    denom = d00 * d11 - d01 * d01
    v = (d11 * d20 - d01 * d21) / denom
    w = (d00 * d21 - d01 * d20) / denom
    u = 1.0 - v - w
    
    vP = u * vA + v * vB + w * vC
  
    return vP

"""
reflect: determine vector "r" is the reflected of vector l over vector n
* l, n: numpy array, shape: (3,); (3,1); (4, ); (4,1)
* return: numpy array, shape (same as l and n)
"""
def reflect(l, n):
    l = np.array(l).reshape(-1, 1)
    n = np.array(n).reshape(-1, 1)
    r = l - 2 * np.dot(l.T, n) * n
    return r.reshape(l.shape)


"""
o2c_vec: 
  >>> vec: a vector in object space
  >>> Mo2c_vec: transformation matrix to transform vector/point from object space to camera space
  >>> o2c_vec transform "vec" to camera space

* Mo2c_vec: numpy array, shape: (4,4)
* vector: vec4d
* return: vec3d
"""
def o2c_vec(Mo2c_vec, vec):
    if vec.shape == (3,1) or vec.shape == (3,) :
        vec = np.append(vec, 1)
    vcam = np.dot(Mo2c_vec, vec)
    return vcam[:3]/vcam[3]


"""
mid_of: determine the middle point point X, Y
* X, Y: numpy array, shape: (3,); (3,1); (4,); (4,1)
* return: numpy array, shape: (4,1)
"""
def mid_of(X, Y):
    if X.shape == (3,):
        X = X.reshape((3, 1))
    if Y.shape == (3,):
        Y = Y.reshape((3, 1))
    if X.shape == (4,):
        X = X.reshape((4, 1))
    if Y.shape == (4,):
        Y = Y.reshape((4, 1))
    
    midpoint = (X + Y) / 2
    
    return midpoint



def identity():
    return np.array([
        [1, 0, 0, 0.],
        [0, 1, 0, 0.],
        [0, 0, 1, 0.],
        [0, 0, 0, 1.]
    ])


## Demos for using functions in Question 1

* Run the following cells in this sections to the output and checking the correctness of your functions

In [67]:
P = np.array([
  [-1.0, 0.0, -1.0], #vertex A
  [+1.0, 0.0, -1.0], #vertex B
  [+1.0, 0.0, +1.0]  #vertex C
]) 
print("Vertices: ")
print(P)

D = np.array([1, 5, 0])

Vertices: 
[[ -1.000   0.000  -1.000]
 [  1.000   0.000  -1.000]
 [  1.000   0.000   1.000]]


In [68]:
A, B, C = P[0,:], P[1,:], P[2,:]
nABC = normal_of_face(A, B, C)
print(nABC)

[  0.000  -1.000   0.000]


In [69]:
AB = point3d(B) - point3d(A)
AC = point3d(C) - point3d(A)
nABC = normal_of(AB, AC)
print(nABC)

[  0.000  -1.000   0.000]


In [70]:
nADB = normal_of_face(A, D, B)
nBDC = normal_of_face(B, D, C)
nACD = normal_of_face(A, C, D)
nD = averaged(nADB, nBDC, nACD)
print("nADB:\n"); print(nADB)
print("nBDC:\n"); print(nBDC)
print("nACD:\n"); print(nACD)
print("nD:\n"); print(nD)

nADB:

[  0.000   0.196  -0.981]
nBDC:

[  1.000   0.000   0.000]
nACD:

[ -0.700   0.140   0.700]
nD:

[[  0.565]
 [  0.633]
 [ -0.529]]


In [71]:
S = area(A, B, C)
print("sABC = ", S)

sABC =  2.0


In [72]:
M = C #np.array([0.5, 0.0, -0.5])
vA, vB, vC = 100, 200, 300
vM = interpolate(A, B, C, vA, vB, vC, M)
print("vM = ", vM)

vM =  300.0


# Question 2: Determine Point D

In [73]:
nBAC =  normal_of_face(B,A,C)
def deter_D(Point=[1, 0, 0], dir=nBAC, distance=5):
    dir_norm = dir / np.linalg.norm(dir)
    D = Point + dir_norm * distance
    return D
  
D = deter_D()

In [74]:
print("Question 2:")
print("nBAC =", nBAC)

print("D= \n"); print(D)

Question 2:
nBAC = [  0.000   1.000  -0.000]
D= 

[  1.000   5.000   0.000]


#Question 3: **Peye**, **Mmodel**, **Mview**, **Mmodel-view (Mmv)**, **Mos2cs_vec**, 

In [75]:
Mmodel = identity()

eye = A - 10*nABC
look = B
up  = np.array([0, 1, 0])
n = eye - look
n = n/np.linalg.norm(n)
u = normal_of(up, n)
v = normal_of(n, u)
d = np.array([
    -np.dot(eye, u),
    -np.dot(eye, v),
    -np.dot(eye, n)
])
Peye = deter_D(A, -nABC, 10)

Mv = np.transpose(np.array([
    [u[0], v[0], n[0], 0],
    [u[1], v[1], n[1], 0],
    [u[2], v[2], n[2], 0],
    [d[0], d[1], d[2], 1]
]))

Mmv = np.matmul(Mv, Mmodel)
Mo2c_vec = np.transpose(np.linalg.inv(Mmv))

print("Question 3:")
print("show formulas for computing Mview (n,u,v, and d) here:")
print("Peye = "); print(Peye)
print("Mview = "); print(Mv)
print("Mmodel = "); print(Mmodel)
print("Mmodelview = Mview x Mmodel ="); print(Mmv)
print("Mo2c_vec = [inv(Mmodelview)]^T = "); print(Mo2c_vec)

Question 3:
show formulas for computing Mview (n,u,v, and d) here:
Peye = 
[ -1.000  10.000  -1.000]
Mview = 
[[  0.000  -0.000   1.000   1.000]
 [  0.981   0.196   0.000  -0.981]
 [ -0.196   0.981   0.000 -10.002]
 [  0.000   0.000   0.000   1.000]]
Mmodel = 
[[  1.000   0.000   0.000   0.000]
 [  0.000   1.000   0.000   0.000]
 [  0.000   0.000   1.000   0.000]
 [  0.000   0.000   0.000   1.000]]
Mmodelview = Mview x Mmodel =
[[  0.000   0.000   1.000   1.000]
 [  0.981   0.196   0.000  -0.981]
 [ -0.196   0.981   0.000 -10.002]
 [  0.000   0.000   0.000   1.000]]
Mo2c_vec = [inv(Mmodelview)]^T = 
[[  0.000   0.000   1.000   0.000]
 [  0.981   0.196   0.000   0.000]
 [ -0.196   0.981   0.000   0.000]
 [ -1.000  10.000  -1.000   1.000]]


#Question 4: **Ac, Bc, Cc**

In [76]:
Ac = Mmv @ point4d(A) #YOUR CODE IS HERE
Bc = Mmv @ point4d(B) #YOUR CODE IS HERE
Cc = Mmv @ point4d(C) #YOUR CODE IS HERE

print("Question4")
print("Ac^T = Mmv x A =", Ac.ravel())
print("Bc^T = Mmv x B =", Bc.ravel())
print("Cc^T = Mmv x C =", Cc.ravel())

Question4
Ac^T = Mmv x A = [  0.000  -1.961  -9.806   1.000]
Bc^T = Mmv x B = [  0.000   0.000 -10.198   1.000]
Cc^T = Mmv x C = [  2.000   0.000 -10.198   1.000]


#Question 5: **Q and Qc**

In [77]:
M = mid_of(A, B)
Q = mid_of(M, D)
Qc = Mmv @ point4d(Q)

print("Question 5:")
print(Q)
print("Qc^T = Mmv x Q =      ", Qc.ravel())


Question 5:
[[  0.500]
 [  2.500]
 [ -0.500]]
Qc^T = Mmv x Q =       [  0.500   0.000  -7.649   1.000]


#Question 6: **Phong Shading**
* Guidelines:
  * Normal vector of each vertex A, B, C: computed by taking the averaged of the normal vector of the three faces shared at those vertices. For example, nA = averaged of nABC, nADB, nACD
  * **to transform a point** from object space (Mo) to camera space (Mcam): Mcam = Mmv x Mo; i.e., using model-view matrix
  * **to transform a vector** from object space (Vo) to camera space (Vcam): Vcam = Mo2c_vec x Vo; i.e., using inverse of transpose of the model-view matrix

In [111]:
K = np.array([
  [0.6, 0.8, 0.8], #diffuse
  [1.0, 0.8, 0.4], #specular
  [0.6, 0.8, 0.2], #ambient
])
I = np.array([
  [1, 0.4, 1], #diffuse
  [1, 0.4, 1], #specular
  [1, 0.4, 1], #ambient
])
shininess = 200
Lpos = np.array([10, 10, -10, 1.0]) # light position


print("Question 6:")
# compute normal vector at vertex
nA = np.mean(np.array([nABC, nADB, nACD]), axis=0)
nB = np.mean(np.array([nABC, nBDC, nADB]), axis=0)
nC = np.mean(np.array([nABC, nACD, nBDC]), axis=0)

#to camera space
Lpos_cam = o2c_vec(Mv, Lpos)
nA_cam = o2c_vec(Mv, nA)
nB_cam = o2c_vec(Mv, nB)
nC_cam = o2c_vec(Mv, nC)

#Interpolate normal vectors
# nQ_cam = interpolate_barycentric(np.array([nA_cam, nB_cam, nC_cam]), barycentric)

print("nA_cam = ", nA_cam.ravel())
print("nB_cam = ", nB_cam.ravel())
print("nC_cam = ", nC_cam.ravel())
print("nQ_cam = ", nQ_cam.ravel())

L = vec3d(Lpos_cam - Qc)
L = (L/np.linalg.norm(L)).ravel()
V = vec3d(vec4d(np.array([0, 0, 0])) - Qc)
V = (V/np.linalg.norm(V)).ravel()
R = reflect(L, nQ_cam).ravel()
N = nQ_cam.ravel()


print("L =" , L.ravel())
print("V =" , V.ravel())
print("N =" , N.ravel())
print("R =" , R.ravel())

#YOUR CODE IS HERE: to compute color of Q (CQ)

print("Color of Q: ", CQ.ravel())


Question 6:
nA_cam =  [  0.907  -1.253 -10.173]
nB_cam =  [  0.673  -0.706 -10.330]
nC_cam =  [  1.233  -0.939 -10.303]


NameError: name 'nQ_cam' is not defined